"""Add password_hash field to user models

Revision ID: 3a8f8c7b2a87
Revises: add_equip_name_idx
Create Date: 2026-01-02 06:55:50.359036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a8f8c7b2a87'
down_revision = 'add_equip_name_idx'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 辅助函数：检查列是否存在
    def column_exists(table_name, column_name):
        conn = op.get_bind()
        result = conn.execute(sa.text(f"""
            SELECT COUNT(*) 
            FROM information_schema.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = '{table_name}' 
            AND COLUMN_NAME = '{column_name}'
        """))
        return result.scalar() > 0
    
    # 只在列不存在时添加
    if not column_exists('admin', 'password_hash'):
        with op.batch_alter_table('admin', schema=None) as batch_op:
            batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=True, comment='密码Hash值'))

    if not column_exists('student', 'password_hash'):
        with op.batch_alter_table('student', schema=None) as batch_op:
            batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=True, comment='密码Hash值'))

    if not column_exists('teacher', 'password_hash'):
        with op.batch_alter_table('teacher', schema=None) as batch_op:
            batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=True, comment='密码Hash值'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 辅助函数：检查列是否存在
    def column_exists(table_name, column_name):
        conn = op.get_bind()
        result = conn.execute(sa.text(f"""
            SELECT COUNT(*) 
            FROM information_schema.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = '{table_name}' 
            AND COLUMN_NAME = '{column_name}'
        """))
        return result.scalar() > 0
    
    # 只在列存在时删除
    if column_exists('teacher', 'password_hash'):
        with op.batch_alter_table('teacher', schema=None) as batch_op:
            batch_op.drop_column('password_hash')

    if column_exists('student', 'password_hash'):
        with op.batch_alter_table('student', schema=None) as batch_op:
            batch_op.drop_column('password_hash')

    if column_exists('admin', 'password_hash'):
        with op.batch_alter_table('admin', schema=None) as batch_op:
            batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
