"""Add description and reject_reason fields to reservation table

Revision ID: add_reservation_desc
Revises: 3a8f8c7b2a87
Create Date: 2026-01-19 11:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_reservation_desc'
down_revision = '3a8f8c7b2a87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True, comment='预约用途说明'))
        batch_op.add_column(sa.Column('reject_reason', sa.String(length=500), nullable=True, comment='拒绝理由'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.drop_column('reject_reason')
        batch_op.drop_column('description')
    # ### end Alembic commands ###
