"""Initial migration

Revision ID: fa98e6e70c2d
Revises: 3a8f8c7b2a87
Create Date: 2026-01-04 10:49:16.412084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa98e6e70c2d'
down_revision = '3a8f8c7b2a87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('fk_1'))
        batch_op.drop_constraint(batch_op.f('fk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'laboratory', ['manage_scope'], ['id'])

    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('fk_1'))
        batch_op.drop_constraint(batch_op.f('fk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'laboratory', ['lab_id'], ['id'])

    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('fk_1'))
        batch_op.drop_index(batch_op.f('fk_2'))
        batch_op.drop_index(batch_op.f('fk_3'))
        batch_op.drop_constraint(batch_op.f('fk_5'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_4'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_6'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'equipment', ['equip_id'], ['id'])
        batch_op.create_foreign_key(None, 'teacher', ['teacher_id'], ['id'])
        batch_op.create_foreign_key(None, 'student', ['student_id'], ['id'])

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('fk_1'))
        batch_op.drop_index(batch_op.f('fk_2'))
        batch_op.drop_constraint(batch_op.f('fk_3'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_4'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'teacher', ['t_id'], ['id'])
        batch_op.create_foreign_key(None, 'laboratory', ['lab_id'], ['id'])

    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('fk_1'))
        batch_op.drop_constraint(batch_op.f('fk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'laboratory', ['lab_id'], ['id'])

    with op.batch_alter_table('timeslot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('fk_1'))
        batch_op.drop_constraint(batch_op.f('fk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'equipment', ['equip_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timeslot', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_2'), 'equipment', ['equip_id'], ['id'], referent_schema='test')
        batch_op.create_index(batch_op.f('fk_1'), ['equip_id'], unique=False)

    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_2'), 'laboratory', ['lab_id'], ['id'], referent_schema='test')
        batch_op.create_index(batch_op.f('fk_1'), ['lab_id'], unique=False)

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_4'), 'teacher', ['t_id'], ['id'], referent_schema='test')
        batch_op.create_foreign_key(batch_op.f('fk_3'), 'laboratory', ['lab_id'], ['id'], referent_schema='test')
        batch_op.create_index(batch_op.f('fk_2'), ['t_id'], unique=False)
        batch_op.create_index(batch_op.f('fk_1'), ['lab_id'], unique=False)

    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_6'), 'equipment', ['equip_id'], ['id'], referent_schema='test')
        batch_op.create_foreign_key(batch_op.f('fk_4'), 'teacher', ['teacher_id'], ['id'], referent_schema='test')
        batch_op.create_foreign_key(batch_op.f('fk_5'), 'student', ['student_id'], ['id'], referent_schema='test')
        batch_op.create_index(batch_op.f('fk_3'), ['teacher_id'], unique=False)
        batch_op.create_index(batch_op.f('fk_2'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('fk_1'), ['equip_id'], unique=False)

    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_2'), 'laboratory', ['lab_id'], ['id'], referent_schema='test')
        batch_op.create_index(batch_op.f('fk_1'), ['lab_id'], unique=False)

    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_2'), 'laboratory', ['manage_scope'], ['id'], referent_schema='test')
        batch_op.create_index(batch_op.f('fk_1'), ['manage_scope'], unique=False)

    # ### end Alembic commands ###
